[connections.default]
warehouse = "QUICKSTART_WH"
role = "ACCOUNTADMIN"
database = "QUICKSTART_COMMON"
schema = "PUBLIC"
account = "GLLADQJ-VO59160"
user = "FAUZAN"
password = "Strong.Passw0rd1!"